-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 22:34:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `id_user` INT NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(80) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Posts` (
  `id_post` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NULL,
  `post_content` TEXT(1500) NOT NULL,
  `status` TINYINT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  `User_id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;

CREATE INDEX `fk_Posts_Admin1_idx` ON `Posts` (`User_id_user` ASC);


-- -----------------------------------------------------
-- Table `Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comments` (
  `id_comment` INT NOT NULL,
  `fk_post_id` INT NULL,
  `author` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `comment_content` VARCHAR(100) NOT NULL,
  `comment_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  `Posts_id_post` INT UNSIGNED NOT NULL,
  `User_id_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`))
ENGINE = InnoDB;

CREATE INDEX `fk_Comments_Posts1_idx` ON `Comments` (`Posts_id_post` ASC);

CREATE INDEX `fk_Comments_Admin1_idx` ON `Comments` (`User_id_user` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
